-- ============================================================
-- SEED DE DATOS - Transfer Class - Modelo de Zonas 2026
-- Generado automáticamente por scripts/generate_seed.py
-- ============================================================

-- 1. Clases de vehículo
insert into public.vehicle_classes (code, name, max_pax, display_order) values
  ('E', 'Mercedes Clase E', 3, 1),
  ('S', 'Mercedes Clase S', 3, 2),
  ('V', 'Clase V', 6, 3)
on conflict (code) do nothing;

-- 2. Zonas (Zona 0 = Aeropuerto, con precio real como cualquier otra zona)
insert into public.zones (zone_number, name, example_locations, is_airport) values
  (0, 'Aeropuerto de Palma (PMI) y alrededores', 'Palma, Arenal, Can Pastilla, S''Aranjassa, Son Ferriol, Sa Casa Blanca, Pont d''Inca, Sant Jordi, Son Rapinya, Son Veri Nou', true),
  (1, 'Ponent y Marratxí', 'Bendinat, Illetes, Cas Català, Son Vida, Marratxí, Llucmajor, Algaida', false),
  (2, 'Calvià y Tramuntana Sur', 'Magaluf, Santa Ponça, Peguera, Valldemossa, Bunyola, Inca, Sineu, Campos', false),
  (3, 'Andratx y Sóller', 'Andratx, Port de Andratx, Deià, Sóller, Port de Sóller, Sa Pobla, Manacor, Santanyí', false),
  (4, 'Pollença y Llevant Nord', 'Pollença, Port de Pollença, Can Picafort, Porto Cristo, Cala d''Or', false),
  (5, 'Artà y Costa Nord-Este', 'Cala San Vicenç, Artà, Cala Millor, Sa Coma, Colònia de Sant Pere', false),
  (6, 'Capdepera', 'Cala Ratjada, Cala Agulla, Cala Mesquida, Capdepera', false),
  (7, 'Sa Calobra (zona remota)', 'Cala Tuent, La Calobra', false)
on conflict (zone_number) do update set name = excluded.name, example_locations = excluded.example_locations, is_airport = excluded.is_airport;

-- 2.1 Localidades reales del tarifario (231, extraídas del PDF y verificadas)
--     + el propio Aeropuerto, para poder buscarlo por nombre igual que el resto.
with zn as (
  select id, zone_number from public.zones
)
insert into public.locations (name, zone_id)
select v.name, zn.id
from (values
  ('Aeropuerto de Palma (PMI)', 0),
  ('Arenal', 0),
  ('Can Pastilla', 0),
  ('Palma', 0),
  ('Pont d''Inca', 0),
  ('S''Aranjassa', 0),
  ('Sa Casa Blanca', 0),
  ('Sant Jordi', 0),
  ('Son Ferriol', 0),
  ('Son Rapinya', 0),
  ('Son Veri Nou', 0),
  ('Algaida', 1),
  ('Badia Blava', 1),
  ('Badia Gran', 1),
  ('Bendinat', 1),
  ('Biniali', 1),
  ('Cala Blava', 1),
  ('Cala Major', 1),
  ('Cas Català', 1),
  ('Costa d''en Blanes', 1),
  ('Cugulutx', 1),
  ('Establiments', 1),
  ('Gènova', 1),
  ('Illetes', 1),
  ('Llucmajor', 1),
  ('Maioris Decima', 1),
  ('Marratxinet', 1),
  ('Marratxí', 1),
  ('Palmañola', 1),
  ('Portals Nous', 1),
  ('Portol', 1),
  ('Puigderrós', 1),
  ('Puntiró', 1),
  ('Randa', 1),
  ('S''Esgleieta', 1),
  ('Sa Cabaneta', 1),
  ('Sa Planera', 1),
  ('Sa Torre', 1),
  ('Sant Agustí', 1),
  ('Santa Eugénia', 1),
  ('Santa Maria del Camí', 1),
  ('Secar de la Real', 1),
  ('Ses Alqueries', 1),
  ('Ses Olleries', 1),
  ('Ses Palmeres', 1),
  ('Ses Rotgetes de Canet', 1),
  ('Son Anglada', 1),
  ('Son Antem', 1),
  ('Son Espanyol', 1),
  ('Son Gual', 1),
  ('Son Roca', 1),
  ('Son Sardina', 1),
  ('Son Vida', 1),
  ('Sonarossa', 1),
  ('Tolleric', 1),
  ('Alaró', 2),
  ('Biniamar', 2),
  ('Binissalem', 2),
  ('Bunyola', 2),
  ('Cala Fornells', 2),
  ('Cala Pi', 2),
  ('Cala Vinyes', 2),
  ('Calvià', 2),
  ('Campos', 2),
  ('Cas Canar', 2),
  ('Caubet', 2),
  ('Consell', 2),
  ('Costa de la Calma', 2),
  ('Costitx', 2),
  ('El Toro', 2),
  ('Es Capdellà', 2),
  ('Es Verger', 2),
  ('Esporles', 2),
  ('Galatzo', 2),
  ('Galilea', 2),
  ('Inca', 2),
  ('Jornets', 2),
  ('La Porrassa', 2),
  ('Laiar', 2),
  ('Lloret de Vistalegre', 2),
  ('Lloseta', 2),
  ('Magaluf', 2),
  ('Montuïri', 2),
  ('Nova Valldemossa', 2),
  ('Orient', 2),
  ('Palmanova', 2),
  ('Peguera', 2),
  ('Pina', 2),
  ('Porreres', 2),
  ('Portals Vells', 2),
  ('Puigpunyent', 2),
  ('Punta Negra', 2),
  ('Rotes Velles', 2),
  ('Ruberts', 2),
  ('S''Arxiduc', 2),
  ('S''Estanyol', 2),
  ('Sa Ràpita', 2),
  ('Sa Vinyola', 2),
  ('Sant Joan', 2),
  ('Santa Ponça', 2),
  ('Sencelles', 2),
  ('Sineu', 2),
  ('Sol de Mallorca', 2),
  ('Son Bieló', 2),
  ('Son Caliu', 2),
  ('Son Ferrandell', 2),
  ('Son Ferrer', 2),
  ('Son Matias', 2),
  ('Son Serralta', 2),
  ('Valldemossa', 2),
  ('Vallgonera', 2),
  ('Alconasser', 3),
  ('Andratx', 3),
  ('Ariany', 3),
  ('Banyalbufar', 3),
  ('Banyos de Sant Joan', 3),
  ('Biniaraix', 3),
  ('Binibona', 3),
  ('Bon Any', 3),
  ('Búger', 3),
  ('Caimari', 3),
  ('Cala Figuera', 3),
  ('Cala Llombards', 3),
  ('Cala Santanyí', 3),
  ('Camp de Mar', 3),
  ('Campanet', 3),
  ('Cas Concos', 3),
  ('Colònia de Sant Jordi', 3),
  ('Deià', 3),
  ('Es Llombards', 3),
  ('Es Palmer', 3),
  ('Es Port', 3),
  ('Es Trenc', 3),
  ('Estellencs', 3),
  ('Felanitx', 3),
  ('Fornalutx', 3),
  ('Llubí', 3),
  ('Llucalcari', 3),
  ('Manacor', 3),
  ('Mancor de la Vall', 3),
  ('Maria de la Salut', 3),
  ('Miramar', 3),
  ('Moscari', 3),
  ('Muro', 3),
  ('Petra', 3),
  ('Port de Andratx', 3),
  ('Port de Sóller', 3),
  ('Port de Valldemossa', 3),
  ('Port des Canonge', 3),
  ('S''Alqueria Blanca', 3),
  ('S''Arracó', 3),
  ('S''Empeltada', 3),
  ('Sa Pobla', 3),
  ('Sa Teulera', 3),
  ('Sant Telm', 3),
  ('Santa Margalida', 3),
  ('Santanyí', 3),
  ('Selva', 3),
  ('Ses Covetes', 3),
  ('Ses Salines', 3),
  ('Son Coll', 3),
  ('Son Gil', 3),
  ('Son Macià', 3),
  ('Son Moja', 3),
  ('Son Negre', 3),
  ('Son Proenç', 3),
  ('Son Talent', 3),
  ('Son Valls', 3),
  ('Sóller', 3),
  ('Ullaró', 3),
  ('Vilafranca de Bonany', 3),
  ('Alcúdia', 4),
  ('Barca Trencada', 4),
  ('Cala Ferrera', 4),
  ('Cala Magrana', 4),
  ('Cala Marsal', 4),
  ('Cala Mendia', 4),
  ('Cala Murada', 4),
  ('Cala Tropicana', 4),
  ('Cala d''Or', 4),
  ('Cales de Mallorca', 4),
  ('Calonge', 4),
  ('Can Picafort', 4),
  ('Crestatx', 4),
  ('El Vilà', 4),
  ('Escorca', 4),
  ('Pollença', 4),
  ('Port de Alcudia', 4),
  ('Port de Pollença', 4),
  ('Porto Cristo', 4),
  ('Portocolom', 4),
  ('Portopetro', 4),
  ('Romántica', 4),
  ('S''Horta', 4),
  ('Sa Marineta', 4),
  ('Sant Llorenç des Cardassar', 4),
  ('Son Carrió', 4),
  ('Son Más', 4),
  ('Son Serra de Marina', 4),
  ('Artà', 5),
  ('Betlem', 5),
  ('Cala Bona', 5),
  ('Cala Carbo', 5),
  ('Cala Millor', 5),
  ('Cala Morlanda', 5),
  ('Cala San Vicenç', 5),
  ('Cases Vellas de Formentor', 5),
  ('Cielo de Bonaire', 5),
  ('Colònia de Sant Pere', 5),
  ('Formentor', 5),
  ('Mal Pas-Bon Aire', 5),
  ('S''Illot', 5),
  ('Sa Coma', 5),
  ('Son Servera', 5),
  ('Cala Agulla', 6),
  ('Cala Gat', 6),
  ('Cala Mesquida', 6),
  ('Cala Ratjada', 6),
  ('Canyamle', 6),
  ('Capdepera', 6),
  ('Costa del Pins', 6),
  ('Es Carregador', 6),
  ('Faro Formentor', 6),
  ('Font de Sa Cala', 6),
  ('La Cassereta', 6),
  ('Pedruscada', 6),
  ('Provensals', 6),
  ('Punta de la Moneia', 6),
  ('Racó d''en Rafal Bei', 6),
  ('Son Moll', 6),
  ('Cala Tuent', 7),
  ('La Calobra', 7)
) as v(name, zone_number)
join zn on zn.zone_number = v.zone_number
on conflict (name) do update set zone_id = excluded.zone_id;

-- 3. Tarifa base por zona y clase de vehículo (SIN IVA)
with cls as (
  select id, code from public.vehicle_classes
),
zn as (
  select id, zone_number from public.zones
)
insert into public.zone_rates (zone_id, vehicle_class_id, price_base)
select zn.id, cls.id, v.price
from (values
  (0, 'E', 53.0),
  (0, 'S', 98.0),
  (0, 'V', 81.0),
  (1, 'E', 58.0),
  (1, 'S', 106.0),
  (1, 'V', 88.0),
  (2, 'E', 72.0),
  (2, 'S', 131.0),
  (2, 'V', 109.0),
  (3, 'E', 85.0),
  (3, 'S', 155.0),
  (3, 'V', 129.0),
  (4, 'E', 106.0),
  (4, 'S', 192.0),
  (4, 'V', 160.0),
  (5, 'E', 117.0),
  (5, 'S', 212.0),
  (5, 'V', 176.0),
  (6, 'E', 126.0),
  (6, 'S', 229.0),
  (6, 'V', 191.0),
  (7, 'E', 135.0),
  (7, 'S', 245.0),
  (7, 'V', 204.0)
) as v(zone_number, class_code, price)
join zn on zn.zone_number = v.zone_number
join cls on cls.code = v.class_code
on conflict (zone_id, vehicle_class_id) do update set price_base = excluded.price_base;

-- 4. Tarifas de disposición por horas (servicio de chófer a horas)
with cls as (
  select id, code from public.vehicle_classes
)
insert into public.disposal_rates (vehicle_class_id, hours, price_base, is_extra_hour)
select cls.id, v.hours, v.price, false
from (values
  (3, 'E', 273.0),
  (3, 'S', 396.0),
  (3, 'V', 355.0),
  (4, 'E', 338.0),
  (4, 'S', 490.0),
  (4, 'V', 440.0),
  (5, 'E', 339.0),
  (5, 'S', 491.0),
  (5, 'V', 441.0),
  (6, 'E', 404.0),
  (6, 'S', 586.0),
  (6, 'V', 526.0),
  (7, 'E', 469.0),
  (7, 'S', 680.0),
  (7, 'V', 611.0),
  (8, 'E', 470.0),
  (8, 'S', 681.0),
  (8, 'V', 612.0),
  (9, 'E', 536.0),
  (9, 'S', 776.0),
  (9, 'V', 697.0),
  (10, 'E', 601.0),
  (10, 'S', 870.0),
  (10, 'V', 782.0),
  (11, 'E', 666.0),
  (11, 'S', 965.0),
  (11, 'V', 867.0),
  (12, 'E', 667.0),
  (12, 'S', 966.0),
  (12, 'V', 868.0)
) as v(hours, class_code, price)
join cls on cls.code = v.class_code
on conflict (vehicle_class_id, hours, is_extra_hour) do update set price_base = excluded.price_base;

-- 5. Precio de hora extra (a partir de la hora 12)
with cls as (
  select id, code from public.vehicle_classes
)
insert into public.disposal_rates (vehicle_class_id, hours, price_base, is_extra_hour)
select cls.id, 0, v.price, true
from (values
  ('E', 65.0),
  ('S', 95.0),
  ('V', 85.0)
) as v(class_code, price)
join cls on cls.code = v.class_code
on conflict (vehicle_class_id, hours, is_extra_hour) do update set price_base = excluded.price_base;
